version: "3.3"
services:
  app:
    build: .
    volumes:
      - ./imgs_vol:/app/src/imgs
    ports:
      - "8080:8080"
    command: bash -c "python -m src.main"
    depends_on:
      - redis
      - db
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=image_microservice
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A src.tasks worker --loglevel=info
    volumes:
      - .:/code
      - ./imgs_vol:/app/src/imgs
    depends_on:
      - db
      - redis
volumes:
  pgdata:
  imgs_vol:


