version: "3.3"
services:
  app_prod:
    build: .
    volumes:
      - ./imgs_vol:/app/src/imgs
    ports:
      - "8080:8080"
    command: bash -c "python -m src.main"
    depends_on:
      - redis_prod
      - db_prod
  db_prod:
    image: "alexlapshev/image_microservice_prod"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis_prod:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
  celery_prod:
    build: .
    command: celery -A src.tasks worker --loglevel=info
    volumes:
      - .:/code
      - ./imgs_vol:/app/src/imgs
    depends_on:
      - db_prod
      - redis_prod
volumes:
  pgdata:
  imgs_vol:


